name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #service locator
  get_it: ^2.0.2
  #bloc for state management
  flutter_bloc: ^0.21.0
  #value equality
  equatable: ^0.4.0
  #functional programming thingies
  dartz: ^0.8.6
  #remote api
  connectivity: ^0.4.3+7
  http: ^0.12.0+2
  #local cache
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/lake.jpg
